/** Single source of truth for cross-context types. Never redeclare these elsewhere. */
import type { TelemetryMetric } from './telemetry-types';

export enum TrackerCategory {
  Advertising = 0,
  Analytics = 1,
  Behavioral = 2,
  Unknown = 3,
}

export interface TrackerHit {
  /** eTLD+1 of the third-party request target. */
  domain: string;
  entityId: string | null;
  category: TrackerCategory;
  hits: number;
  firstSeenAt: number;
}

export interface TabLedger {
  tabId: number;
  pageDomain: string | null;
  startedAt: number;
  /** Keyed by eTLD+1. */
  trackers: Record<string, TrackerHit>;
  /** Third-party requests seen on this page, including ones past the cap. */
  requests: number;
  /** True once the per-page request cap is hit; `hits` stop incrementing. */
  capped: boolean;
}

export interface CategoryTotals {
  [TrackerCategory.Advertising]: number;
  [TrackerCategory.Analytics]: number;
  [TrackerCategory.Behavioral]: number;
  [TrackerCategory.Unknown]: number;
}

export interface LedgerSummary {
  tabId: number;
  pageDomain: string | null;
  /** Distinct third-party domains observed. */
  total: number;
  byCategory: CategoryTotals;
  topEntity: { id: string; name: string; count: number } | null;
  capped: boolean;
}

/* ------------------------------------------------------------------ */
/* Tracker dictionary (generated by tools/build-tracker-db.mjs)        */
/* ------------------------------------------------------------------ */

export interface EntityRecord {
  name: string;
  displayName: string;
}

/** `[entityId, categoryCode]`, kept as a tuple to keep the artifact small. */
export type HostRecord = [entityId: string | null, category: number];

export interface TrackerDictionary {
  version: string;
  generatedAt: string;
  sources: { id: string; title: string; license: string; attribution: string }[];
  categories: string[];
  entities: Record<string, EntityRecord>;
  /** Keyed by hostname, not eTLD+1. See docs/ADR-002. */
  hosts: Record<string, HostRecord>;
}

/* ------------------------------------------------------------------ */
/* Messaging                                                           */
/* ------------------------------------------------------------------ */

export const PORT_NAME = 'ghostprint';

/** One row in the expanded panel. */
export interface TrackerDetail {
  domain: string;
  entityId: string | null;
  entityName: string | null;
  category: TrackerCategory;
  hits: number;
}

export interface EntityCount {
  id: string;
  name: string;
  count: number;
}

export interface HistorySummary {
  /** Size of the rolling window, in days. */
  days: number;
  /** Tracker encounters across the window, not distinct domains. */
  total: number;
  distinctDomains: number;
  byCategory: CategoryTotals;
  topEntities: EntityCount[];
}

/** Privacy-safe weekly share summary; contains no first-party site or full URL. */
export interface WeeklyReport {
  weekStarting: string;
  weekEnding: string;
  totalTrackers: number;
  previousTotal: number;
  deltaCount: number;
  deltaPercent: number | null;
  topTrackerDomain: string | null;
  topEntityName: string | null;
  estimatedValue: number;
}

/** Requests initiated by content script / popup / options, answered by the SW. */
export type Request =
  | { type: 'PING' }
  | { type: 'GET_LEDGER'; tabId?: number }
  | { type: 'GET_DETAILS'; tabId?: number }
  | { type: 'GET_HISTORY'; days?: number }
  | { type: 'GET_WEEKLY_REPORT' }
  | { type: 'TRACK_TELEMETRY'; metric: TelemetryMetric }
  | { type: 'GET_TELEMETRY_STATUS' }
  | { type: 'TOGGLE_XRAY' }
  | { type: 'CLEAR_ALL_DATA' };

export type ResponseFor<R extends Request> = R extends { type: 'PING' }
  ? { type: 'PONG'; at: number }
  : R extends { type: 'GET_LEDGER' }
    ? { type: 'LEDGER'; summary: LedgerSummary | null }
    : R extends { type: 'GET_DETAILS' }
      ? { type: 'DETAILS'; trackers: TrackerDetail[] }
      : R extends { type: 'GET_HISTORY' }
        ? { type: 'HISTORY'; summary: HistorySummary }
          : R extends { type: 'GET_WEEKLY_REPORT' }
            ? { type: 'WEEKLY_REPORT'; report: WeeklyReport }
            : R extends { type: 'TRACK_TELEMETRY' }
              ? { type: 'TRACKED'; accepted: boolean }
              : R extends { type: 'GET_TELEMETRY_STATUS' }
                ? { type: 'TELEMETRY_STATUS'; endpointConfigured: boolean; destination: string | null }
                : R extends { type: 'TOGGLE_XRAY' }
                  ? { type: 'XRAY_TOGGLED' }
                  : R extends { type: 'CLEAR_ALL_DATA' }
                    ? { type: 'CLEARED' }
                    : never;

/** Pushed from the SW to connected ports. */
export type Push =
  | { type: 'LEDGER_DELTA'; summary: LedgerSummary }
  | { type: 'LEDGER_RESET'; tabId: number };

export interface ErrorResponse {
  type: 'ERROR';
  message: string;
}
